# -*- coding: utf-8 -*-
"""BOJ_18352.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GqY3nDOwXyKJBFzexyQy7mCCHo0C2nvO
"""

from collections import deque
from sys import stdin
input = stdin.readline()

N,M,K,X = map(int,input().split())

a = [[] for _ in range(N+1)]
dist = [False for _ in range(N+1)]

for _ in range(M):
    u,v=  map(int,input().split())
    a[u].append(v)
    



q = deque()
q.append((X,0))
dist[X] = True
res = []

while q:
    x, c = q.popleft()
    c += 1
    for y in a[x]:
        if dist[y] == False:
            dist[y] = True
            if c == K:
                res.append(y)
            q.append((y, c))
    
res.sort()


if len(res) == 0:
    print(-1)
else:
    for i in res:
        print(i)

