# -*- coding: utf-8 -*-
"""프로그래머스_모의고사.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jFd52Z55HSi36NfntEdCCoQP0U79lJt
"""

def solution(answers):
    answer = []
    p1 = [1,2,3,4,5]
    p2 = [2,1,2,3,2,4,2,5]
    p3 = [3,3,1,1,2,2,4,4,5,5]
    ls1 = []
    ls2 = []
    ls3 = []
    cnt = [0,0,0,0]
    i = 0
    while i < len(answers):
        ls1.append(p1[i%len(p1)])
        ls2.append(p2[i%len(p2)])
        ls3.append(p3[i%len(p3)])
        i += 1

    for i in range(len(answers)):
        if answers[i] == ls1[i]:
            cnt[1] += 1
        if answers[i] == ls2[i]:
            cnt[2] += 1
        if answers[i] == ls3[i]:
            cnt[3] += 1

    answer = [i for i in range(len(cnt)) if cnt[i] == max(cnt)]
    return answer