# -*- coding: utf-8 -*-
"""프로그래머스_로또의 최고 순위와 최저 순위.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jFd52Z55HSi36NfntEdCCoQP0U79lJt
"""

def solution(lottos, win_nums):
    cnt_best = 0
    cnt_worst = 0
    
    for i in lottos:
        if i != 0:
            if i in win_nums:
                cnt_best += 1
                cnt_worst += 1
        else:
            cnt_best += 1
            
    answer = [7-i if i >= 1 else 6 for i in [cnt_best, cnt_worst]]
    return answer