# -*- coding: utf-8 -*-
"""프로그래머스_내적.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jFd52Z55HSi36NfntEdCCoQP0U79lJt
"""

def solution(a, b):
    return sum(list(a[i] * b[i] for i in range(len(a))))