# -*- coding: utf-8 -*-
"""BOJ2608.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15u7yq1omYAZ4Utv3m2SurFs1N7jwqqhi
"""

di = {"I" : 1, "V" :5, "X" : 10, "L" :50, "C" :100, "D" :500, "M" :1000}
ls = list()
for i in range(2):
    ls.append(input())

result = 0
result2 = ''

for rom in ls:
    if len(rom) == 1:
        result += di[rom]
    else:
        for i in range(len(rom)-1):
            if di[rom[i]] < di[rom[i+1]]:
                result -= di[rom[i]]
            else:
                result += di[rom[i]]
        result += di[rom[i+1]]


com4 = result // 1000
rest4 = result % 1000

com3 =  rest4 // 100
rest3 = rest4 % 100

com2 = rest3 // 10
rest2 = rest3 % 10

com1 = rest2

list4 = [0,'M','MM','MMM']
list3 = [0,'C','CC','CCC','CD','D','DC','DCC','DCCC','CM']
list2 = [0,'X','XX','XXX','XL','L','LX','LXX','LXXX','XC']
list1 = [0,'I','II','III','IV','V','VI','VII','VIII','IX']

final_list = [[com4,list4], [com3, list3], [com2, list2], [com1, list1]]

for i, u in final_list:
    if i >= 1:
        result2 += u[i]

print(result)
print(result2)