# -*- coding: utf-8 -*-
"""BOJ_2564.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izwCJbPGLRCKjNHzwHyjZW2asZvIeYVf
"""

m, n = map(int, input().split())
t = int(input())
dist = 2*m + 2*n
ls = list()

def location(a,b):
    if a == 1:
        return b
    elif a == 2:
        return m + n + (m-b)
    elif a == 3:
        return 2 * m + n + (n - b)
    elif a == 4:
        return m + b

for _ in range(t):
    a, b = map(int, input().split())
    ls.append(location(a,b))

a, b = map(int, input().split())
main = location(a, b)

result = 0

for i in ls:
    if i < main:
        run = min(i + (dist-main), main-i)
    elif i > main:
        run = min(main + (dist-i), i-main)
    result += run
print(result)