# -*- coding: utf-8 -*-
"""boj_1717.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Du2w4vqcdGqQPGDQlzoVKpeLqiDxr0YC
"""

a, b = map(int, input().split())
def gcd(a, b):
    if b == 0:
        return a
    d = a%b
    return gcd(b,d)
k = gcd(a, b)

print('1'*k)