# -*- coding: utf-8 -*-
"""프로그래머스 - 오픈채팅방.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bgVRVKNdJIKRseSdFK0eUjFT4zz4SIQS
"""

def solution(record):
    answer = []
    di = {}

    for u in record:
        i = u.split()
        if i[0] == "Enter":
            di[i[1]] = i[2]
        elif i[0] == "Change":
            di[i[1]] = i[2]

    for u in record:
        i = u.split()
        if i[0] == "Enter":
            answer.append("{}님이 들어왔습니다.".format(di[i[1]]))
        elif i[0] == "Leave":
            answer.append("{}님이 나갔습니다.".format(di[i[1]]))
    return answer

