# -*- coding: utf-8 -*-
"""프로그래머스-타켓 넘버.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ygqkhckF8GG5PVidmpSgwWY9yPWe8b85
"""

def solution(numbers, target):
    def dfs(numbers, target, depth):
        answer = 0
        
        if depth == len(numbers):
            if sum(numbers) == target:
                return 1
            else:
                return 0
        
        else:
            answer += dfs(numbers, target, depth+1)
            numbers[depth] *= -1
            answer += dfs(numbers, target, depth+1)
        return answer
            
    
    return dfs(numbers,target,0)