# -*- coding: utf-8 -*-
"""BOJ_1931.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7RQ36kPhWWIyeQt9gne5zcV4cA4ta3E
"""

n = 11
n = int(input())
ls2 = []
for i in range(n):
    a, b = map(int, input().split())
    ls2.append([b,a])

ls2.sort()
ls = []
for b, a in ls2:
    ls.append((a,b))

t = ls[0][1]
cnt = 1
if len(ls) >= 2:
    for i, u in ls[1:]:
        if i >= t:
            t = u
            cnt += 1
print(cnt)