# -*- coding: utf-8 -*-
"""프로그래머스_정수 삼각형.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jFd52Z55HSi36NfntEdCCoQP0U79lJt
"""

def solution(triangle):
    n = len(triangle)
    dp = [[0 for _ in range(n)] for _ in range(n)]
    dp[0][0] = triangle[0][0]
    
    for i in range(1, n):
        for u in range(n):
            if u == 0:
                dp[i][u] = dp[i-1][u] + triangle[i][u]
            elif u == len(triangle[i-1]):
                dp[i][u] = dp[i-1][u-1] + triangle[i][u]
            elif 0 < u < len(triangle[i-1]):
                dp[i][u] = max(dp[i-1][u-1], dp[i-1][u]) + triangle[i][u]
    answer = max(dp[-1])
    return answer