# -*- coding: utf-8 -*-
"""프로그래머스_등굣길.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jFd52Z55HSi36NfntEdCCoQP0U79lJt
"""

def solution(m, n, puddles):
    dx, dy = [0,1], [1,0]
    
    for i in range(len(puddles)):
        puddles[i][0] -= 1
        puddles[i][1] -= 1
    
    graph = [[-1 for _ in range(m)] for _ in range(n)]
    
    for i, u in puddles:
        graph[u][i] = -2
        
    
    def dfs(x, y):
        if x == n-1 and y == m-1:
            return 1

        if graph[x][y] == -1:
            graph[x][y] = 0
            for i in range(2):
                nx, ny = x + dx[i], y + dy[i]
                if 0 <= nx < n and 0 <= ny < m:
                    if graph[nx][ny] != -2:
                        graph[x][y] += dfs(nx, ny)
        return graph[x][y]
    answer = dfs(0,0)
    return answer% 1000000007