# -*- coding: utf-8 -*-
"""BOJ_1890.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rnZTtgt_g7BC33ZU9IcR3sncX5sAVHnV
"""

n = int(input())
ls = []
dp = [[-1 for _ in range(n)] for _ in range(n)]
for _ in range(n):
    ls.append(list(map(int, input().split())))
dx, dy = [1,0], [0,1]


def jump(x,y):
    if x == n-1 and y == n-1:
        return 1

    if dp[x][y] == -1:
        dp[x][y] = 0
        for i in range(2):
            nx, ny = x + dx[i] * ls[x][y] , y + dy[i] * ls[x][y]
            if 0 <= nx < n and 0 <= ny < n:
                dp[x][y] += jump(nx,ny)
    return dp[x][y]


print(jump(0,0))